"""Original synthetic media with independent geometry and audio cues."""

import argparse
from pathlib import Path
import json
import subprocess
import wave
import numpy as np
from PIL import Image, ImageDraw


def generate(folder):
    folder = Path(folder)
    folder.mkdir(parents=True, exist_ok=True)
    frames = folder / "frames"
    frames.mkdir(exist_ok=True)
    annotations = []
    for i in range(60):
        image = Image.new("RGB", (160, 96), (18, 30, 48))
        draw = ImageDraw.Draw(image)
        x = 10 + i
        draw.rectangle((x, 24, x + 23, 55), fill=(235, 110, 40))
        image.save(frames / f"{i:06d}.png")
        annotations.append(
            {"frame": i, "rectangle": [x / 160, 24 / 96, (x + 24) / 160, 56 / 96]}
        )
    audio = np.zeros(96000, np.float64)
    for when in (0.1, 0.9, 1.7):
        start = round(when * 48000)
        n = 960
        audio[start : start + n] = 0.6 * np.sin(2 * np.pi * 880 * np.arange(n) / 48000)
    with wave.open(str(folder / "cue.wav"), "wb") as f:
        f.setnchannels(1)
        f.setsampwidth(2)
        f.setframerate(48000)
        f.writeframes((audio * 32767).astype("<i2").tobytes())
    base = [
        "ffmpeg",
        "-v",
        "error",
        "-y",
        "-framerate",
        "30",
        "-i",
        str(frames / "%06d.png"),
    ]
    subprocess.run(
        base
        + [
            "-i",
            str(folder / "cue.wav"),
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-t",
            "2",
            str(folder / "moving.mp4"),
        ],
        check=True,
    )
    subprocess.run(
        base
        + [
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-t",
            "2",
            str(folder / "silent.mp4"),
        ],
        check=True,
    )
    subprocess.run(
        base
        + [
            "-itsoffset",
            "0.2",
            "-i",
            str(folder / "cue.wav"),
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-t",
            "2",
            str(folder / "offset.mp4"),
        ],
        check=True,
    )
    subprocess.run(
        [
            "ffmpeg",
            "-v",
            "error",
            "-y",
            "-display_rotation",
            "90",
            "-i",
            str(folder / "silent.mp4"),
            "-c",
            "copy",
            str(folder / "rotated.mp4"),
        ],
        check=True,
    )
    concat = (
        "".join(
            f"file '{(frames / f'{i:06d}.png').resolve()}'\nduration {duration}\n"
            for i, duration in enumerate([0.04, 0.08, 0.12, 0.04, 0.1, 0.07])
        )
        + f"file '{(frames / '000006.png').resolve()}'\n"
    )
    (folder / "vfr.txt").write_text(concat)
    subprocess.run(
        [
            "ffmpeg",
            "-v",
            "error",
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            str(folder / "vfr.txt"),
            "-fps_mode",
            "vfr",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            str(folder / "vfr.mp4"),
        ],
        check=True,
    )
    (folder / "annotations.json").write_text(
        json.dumps(
            {
                "license": "Original synthetic fixture generated by Rototools; CC0",
                "geometry": annotations,
                "audioCues": [0.1, 0.9, 1.7],
                "audioOffsetCues": [0.3, 1.1, 1.9],
            }
        )
    )
    (folder / "corrupt.mp4").write_bytes(b"not a video")
    return folder


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("folder", nargs="?", default="work/fixtures")
    generate(p.parse_args().folder)
